# Use an official Node.js runtime as a parent image
FROM node:20

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY ../frontend/package*.json ./

# Install any needed packages
RUN npm install

# Bundle app source
COPY ../frontend/ .

# # Build your app
RUN npm run build

# Allow HTTP access
EXPOSE 80

# # Install serve and serve your React app
RUN npm install -g serve
CMD ["serve", "-s", "build", "-l", "0.0.0.0:80"]
